#############################################################################
# Database Configuration
#############################################################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogger_app
    username: root
    password: pass
  application:
    name: Blogger-App
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #############################################################################
  # Hibernate Configuration
  #############################################################################
  jpa:
    hibernate:
      ddl-auto: update

#      Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnYW5nQGdtYWlsLmNvbSIsImlhdCI6MTcxMjY0OTExNywiZXhwIjoxNzEyNjUwNTU3fQ.Y39fuboYBYsEyBXSjp1IWtzrc9RdkCzqOLZrvouqUpo